# .github/workflows/deploy.yml

name: dev
on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    name: dev-deploy
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npx @serverless/cloud test
      - run: npx @serverless/cloud deploy dev
